Mão na massa

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Exercício 1
np.random.seed(2)
E1=np.random.randint(0,100,(10))
print(E1)
print(E1.dtype)

[40 15 72 22 43 82 75  7 34 49]
int32


In [7]:
#Exercício 2
np.random.seed(2)
E2=np.random.rand(5,5).round(2)
print(E2)
print('Máximo: ',round(E2.max(),2))
print('Mínimo: ',E2.min())
print('Média: ',E2.mean())

[[0.44 0.03 0.55 0.44 0.42]
 [0.33 0.2  0.62 0.3  0.27]
 [0.62 0.53 0.13 0.51 0.18]
 [0.79 0.85 0.49 0.85 0.08]
 [0.51 0.07 0.43 0.1  0.13]]
Máximo:  0.85
Mínimo:  0.03
Média:  0.3948000000000001


In [9]:
#Exercício 3
np.random.seed(2)
E3=np.random.rand(10)
print(E3)
print(E3.dtype)

E3_1=(E3*10).astype(int)
print(E3_1.dtype)
E3_1

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678  0.33033482
 0.20464863 0.61927097 0.29965467 0.26682728]
float64
int32


array([4, 0, 5, 4, 4, 3, 2, 6, 2, 2])

In [11]:
#Exercício 4
np.random.seed(2)
E4=np.random.randint(0,9,(3,3))
print(E4)
E4[1,:]=-1
print(E4)


[[8 8 6]
 [2 8 7]
 [2 1 5]]
[[ 8  8  6]
 [-1 -1 -1]
 [ 2  1  5]]


In [12]:
E4[1]

array([-1, -1, -1])

In [ ]:
#Exercício 5 - forma 1
pd.DataFrame([['Banana', 7.90, 12],['Maça', 10.20, 3],['Pera', 11.80, 4]], columns=['fruta', 'preco', 'quantitade'])

fruta  preco  quantitade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4

In [14]:
#Exercício 5 - forma 2
df=pd.DataFrame()
df['fruta'] = ['Banana', 'Maça', 'Pera']
df['preco'] = [7.90, 10.20, 11.80]
df['quantidade'] = [12, 3, 4]
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4