Introdução ao NUMPY

In [ ]:
# pip install numpy

In [1]:
##Importação
import numpy as np

In [2]:
##Arrays - construção
#escalar
print('Escalar\n',5,'\n')

#vetor linha
print('Vetor linha\n', np.array([1,2,3]),'\n')

#vetor coluna
print('Vetor coluna\n', np.array([[1,2,3]]),'\n')

#matriz
print('Matriz\n', np.array([[1,2,3],[4,5,6]]), '\n')

#tensor
print('Tensor\n', np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))


Escalar
 5 

Vetor linha
 [1 2 3] 

Vetor coluna
 [[1 2 3]] 

Matriz
 [[1 2 3]
 [4 5 6]] 

Tensor
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
##Arrays - atributos
#dtype
array_matriz_1=np.array([[1,2,3],[4,5,6]])
print('Tipo matriz 1: ',array_matriz_1.dtype)
array_matriz_2=np.array([[1.0,2,3,4],[4,5,6,4],[10,8,4,20]])
print('Tipo matriz 2: ',array_matriz_2.dtype)
#shape
print('dimensão matriz 1: ',array_matriz_1.shape)
print('dimensão matriz 2: ',array_matriz_2.shape)

Tipo matriz 1:  int32
Tipo matriz 2:  float64
dimensão matriz 1:  (2, 3)
dimensão matriz 2:  (3, 4)


In [4]:
array_matriz_2

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  4.],
       [10.,  8.,  4., 20.]])

In [6]:
type(array_matriz_2)

numpy.ndarray

In [7]:
##Arrays - construção padronizada
#arrays de uns
print('arrays de uns\n', np.ones((3,3)), '\n')

#arrays de zeros
print('arrays de zeros\n', np.zeros((5,2)), '\n')

#arrays com números identicos
print('arrays de valores identicos\n', np.full((2,10),51), '\n')


arrays de uns
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

arrays de zeros
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

arrays de valores identicos
 [[51 51 51 51 51 51 51 51 51 51]
 [51 51 51 51 51 51 51 51 51 51]] 



In [11]:
##Arrays - aleatórios
#Rand
print(np.random.rand(2,3).round(3))
#Randint
np.random.randint(0,10,(3,3))

[[0.49  0.881 0.159]
 [0.064 0.811 0.707]]


array([[9, 5, 9],
       [8, 7, 7],
       [7, 8, 6]])

In [33]:
##Arrays - indexação
np.random.seed(1548)
matriz=np.random.randint(0,100,(4,4))
matriz

array([[84,  8,  2,  0],
       [39, 89, 70, 12],
       [ 5, 10, 53,  5],
       [ 5, 74,  1, 98]])

In [44]:
matriz2=np.random.randint(0,100,(4,4))
matriz2

array([[69, 45, 48, 58],
       [98, 16, 56, 24],
       [80, 89, 26,  5],
       [57, 91, 73, 63]])

In [26]:
matriz[:3,1: ]

array([[20, 37, 39],
       [ 4, 42, 51],
       [33, 58, 67]])

In [27]:
##Arrays - operações
np.linalg.det(matriz)

1393133.0000000012

In [28]:
matriz.sum()

817

In [30]:
matriz.max()

90

In [34]:
matriz

array([[84,  8,  2,  0],
       [39, 89, 70, 12],
       [ 5, 10, 53,  5],
       [ 5, 74,  1, 98]])

In [ ]:
##Arrays - Where
teste=np.where(matriz<40, 'reprovado', 
               np.where(matriz<60, 'recuperação',matriz ))
teste

array([['84', 'reprovado', 'reprovado', 'reprovado'],
       ['reprovado', '89', '70', 'reprovado'],
       ['reprovado', 'reprovado', 'recuperação', 'reprovado'],
       ['reprovado', '74', 'reprovado', '98']], dtype='<U11')

Introdução ao Pandas

In [ ]:
# pip install pandas

In [37]:
import pandas as pd

In [39]:
#Tipo Series
serie=pd.Series(np.array([1,2,3]))
type(serie)

pandas.core.series.Series

In [42]:
#Tipo DataFrame
df=pd.DataFrame(matriz, columns=['portugues', 'matematica', 'ciencias', 'geografia'])
type(df)

pandas.core.frame.DataFrame

In [47]:
df

portugues  matematica  ciencias  geografia
0         84           8         2          0
1         39          89        70         12
2          5          10        53          5
3          5          74         1         98

In [43]:
pd.DataFrame(matriz, columns=['portugues', 'matematica', 'ciencias', 'geografia'], index=['ana', 'paula', "joão", 'cassio'])

portugues  matematica  ciencias  geografia
ana            84           8         2          0
paula          39          89        70         12
joão            5          10        53          5
cassio          5          74         1         98

In [49]:
pd.DataFrame(matriz2)

0   1   2   3
0  69  45  48  58
1  98  16  56  24
2  80  89  26   5
3  57  91  73  63